Made better config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,6 +8,43 @@ orbs:
   run-with-retry-and-clean: andreasmarkussen/run-with-retry-and-clean@0.1.0
   
 
+jobs:
+  build:
+    docker:
+      - image: alpine:3.7
+    steps:
+      - checkout
+      - run:
+          name: The First Step
+          command: |
+            echo 'Hello World!'
+            echo 'This is the delivery pipeline'
+      - run:
+          name: Code Has Arrived
+          command: |
+            ls -al
+            echo '^^^That should look familiar^^^'
+
+  test:
+    docker:
+      - image: alpine:3.7    
+    steps:
+      - checkout
+      - run:
+          name: Create folder that will block things
+          command: |
+            mkdir -p ~/blocking-folder 
+            echo JunkFile > ~/blocking-folder/data.txt
+            ls -la ~/blocking-folder
+      - run-with-retry-and-clean:
+          name: Run commands
+          command: |
+            echo "I will exit fail status"
+            bash my-test.sh
+            exit 1
+          clean-command: |
+            rm -f blocking-files
+
 # Orchestrate or schedule a set of jobs
 workflows:
   # Name the workflow "welcome"
@@ -15,3 +52,5 @@ workflows:
     # Run the welcome/run job in its own container
     jobs:
       - welcome/run
+      - build
+      # - test
